### ISSUE TITLE
it doesn't come out formatted properly, you should not hardcode it. :D 

### ISSUE THREAD

**Issue by StefanoSilv** [jessicakwak/k-03-class#3]
https://github.com/jessicakwak/k-03-class/blob/39d8d636bd2cd56e842798ce5fcb0cfd38c10926/classes.js#L141

**Comment by jessicakwak** [comment]
Gotcha. Make it dynamic so every line is with the same length I guess?

**Comment by StefanoSilv** [comment]
Yes, exactly, taking as point of reference the length of the longest element.

**Comment by jessicakwak** [comment]
Resolved.
